### ISSUE TITLE
MRecordRTC demo not working on Firefox and Chrome

### ISSUE THREAD

**Issue by MikeHoffert** [muaz-khan/WebRTC-Experiment#364]
Referring to the demo [here](https://www.webrtc-experiment.com/RecordRTC/MRecordRTC/).

On Firefox, the page alerts a `{}` and no video preview is available. There are no console errors. Only output to console is statistics about the number of watchers, forks, and followers (unrelated).

In Chrome, there's a preview (and audio can be heard), however, the save button is not available on stopping the recording (or ever) and the console logs the following error:

>Uncaught TypeError: Cannot read property 'sampleRate' of undefined

I've also got this error in my very minimalistic test of creating an `MRecordRTC`.

In my own test, I fixed this with:

    recorder.sampleRate = 44100;

It seems that this is not being given a default value as it is in `RecordRTC`. But Firefox doesn't save anything at all (Chrome works as expected). I can copy the URL from `stopRecording` into another tab, and the recording is there and correct.

Perhaps of note is that `recorder.writeToDisk()` results in an error:

    TypeError: indexedDB is undefined

I think it's because the prefixed version is no longer supported in Firefox and you aren't using the non-prefixed version (simply `indexedDB `). As a result, this is probably unrelated.

This is using the version downloaded via NPM on Windows 8.1 using the current stable version of Firefox (40.0.2).

**Comment by MikeHoffert** [comment]
I did some experimentation and digging into how you created the download mechanism. It seems that the underlying URL doesn't work (?). Going to the URL directly just doesn't load anything at all. Like, the network tab doesn't even recognize visiting a page and we're still on the new tab page.

I think the URL is wrong. If I copy the URL that stopRecording gets and set the anchor's href to that, then the downloading works. Not sure why.

**Comment by muaz-khan** [comment]
All three issues should be fixed in this commit: https://github.com/muaz-khan/RecordRTC/commit/ffcce50c527a631e8a393be50849e165cf233cea

**Comment by MikeHoffert** [comment]
The main issues seem fixed, but Firefox is still unable to save the recording. Verified against the demo with FF 40.0.3 on Win 8.1.

**Comment by muaz-khan** [comment]
Firefox save-as dialog issue is fixed in this commit: https://github.com/muaz-khan/RecordRTC/commit/52b97aed96ee5b3ad57cfa4297c6ac109bcb2450

**Comment by MikeHoffert** [comment]
Confirmed as fixed.
